name: CodexTestDemo
options:
  bundleIdPrefix: com.codex
  deploymentTarget:
    iOS: "15.0"
targets:
  CodexTestDemo:
    type: application
    platform: iOS
    sources: [CodexTestDemo]
    dependencies:
      - package: Moya
      - package: SnapKit
    settings:
      base:
        INFOPLIST_FILE: CodexTestDemo/SupportingFiles/Info.plist

packages:
  Moya:
    url: https://github.com/Moya/Moya.git
    from: 15.0.0
  SnapKit:
    url: https://github.com/SnapKit/SnapKit.git
    from: 5.0.0
